---
version: 1
guid: "1175543c-6d20-4cfa-93a6-1476836df34c"
name: "Auto Backup"
description: "Automated scheduled ZIP backups of Jellyfin data."
overview: "Automated scheduled ZIP backups of Jellyfin data."
owner: "Filtik"
category: "General"
imageUrl: "https://gitea.home.filtik.de/Filtik/Jellyfin-AutoBackup/raw/branch/main/images/logo.png"
artifacts:
  - "Jellyfin.Plugin.AutoBackup.dll"
targetAbi: "10.11.0.0"
changelog: ""
